right_format = """
$nodejs
$cmd_duration
"""

scan_timeout = 10
add_newline = false

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"

# [custom.arch]
# command = "uname -m"
# when = """ test $(uname -m) = "x86_64" """
# style = "bold yellow"
# format = "[$output]($style)"

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "


[cmd_duration]
format = "took [$duration]($style) "
