-- 一時的にプラグインを無効化
return {}

-- return {
--   "telescope.nvim",
--   dependencies = {
--     "nvim-telescope/telescope-file-browser.nvim",
--   },
--   keys = {
--     { "<leader><leader>", nil }, -- lazyvimのデフォルトキーマップを無効化
--     { "<leader>ff", LazyVim.pick("files"), desc = "Find Files (cwd)" }, -- lazyvimのデフォルト微調整
--     { "<leader>fF", LazyVim.pick("files", { cwd = false }), desc = "Find Files (root dir)" }, -- lazyvimのデフォルト微調整
--     {
--       "<leader>se",
--       function()
--         local builtin = require("telescope.builtin")
--         builtin.diagnostics()
--       end,
--       desc = "Lists Diagnostics for all open buffers or a specific buffer",
--     },
--     {
--       "<leader>si",
--       function()
--         local builtin = require("telescope.builtin")
--         builtin.treesitter()
--       end,
--       desc = "Lists Function names, variables, from Treesitter",
--     },
--     {
--       "<leader>sf",
--       function()
--         local telescope = require("telescope")

--         local function telescope_buffer_dir()
--           return vim.fn.expand("%:p:h")
--         end

--         telescope.extensions.file_browser.file_browser({
--           path = "%:p:h",
--           cwd = telescope_buffer_dir(),
--           respect_gitignore = false,
--           hidden = true,
--           grouped = true,
--           previewer = true,
--           initial_mode = "normal",
--           layout_config = { height = 40 },
--         })
--       end,
--       desc = "Open File Browser with the path of the current buffer",
--     },
--     {
--       "<leader>sF",
--       function()
--         local telescope = require("telescope")
--         telescope.extensions.file_browser.file_browser({
--           cwd = false,
--           respect_gitignore = false,
--           hidden = true,
--           grouped = true,
--           previewer = true,
--           initial_mode = "normal",
--           layout_config = { height = 40 },
--         })
--       end,
--       desc = "Open File Browser with the path of root dir",
--     },
--   },
--   config = function(_, opts)
--     local telescope = require("telescope")
--     local actions = require("telescope.actions")
--     local fb_actions = require("telescope").extensions.file_browser.actions

--     opts.defaults = vim.tbl_deep_extend("force", opts.defaults, {
--       wrap_results = true,
--       layout_strategy = "horizontal",
--       layout_config = { prompt_position = "top" },
--       sorting_strategy = "ascending",
--       winblend = 0,
--       mappings = {
--         n = {},
--       },
--     })

--     opts.extensions = {
--       file_browser = {
--         theme = "dropdown",
--         -- disables netrw and use telescope-file-browser in its place
--         hijack_netrw = true,
--         mappings = {
--           -- your custom insert mode mappings
--           ["n"] = {
--             -- your custom normal mode mappings
--             ["a"] = fb_actions.create,
--             ["m"] = fb_actions.move,
--             ["d"] = fb_actions.remove,
--             ["h"] = fb_actions.goto_parent_dir,
--             ["/"] = function()
--               vim.cmd("startinsert")
--             end,
--             ["<C-u>"] = function(prompt_bufnr)
--               for _ = 1, 10 do
--                 actions.move_selection_previous(prompt_bufnr)
--               end
--             end,
--             ["<C-d>"] = function(prompt_bufnr)
--               for _ = 1, 10 do
--                 actions.move_selection_next(prompt_bufnr)
--               end
--             end,
--             ["<PageUp>"] = actions.preview_scrolling_up,
--             ["<PageDown>"] = actions.preview_scrolling_down,
--           },
--         },
--       },
--     }

--     telescope.setup(opts)
--     require("telescope").load_extension("fzf")
--     require("telescope").load_extension("file_browser")
--   end,
-- }
